(define (sum-of-two-max x y z)
    (cond
        ((< x y)
            (if (< x z)
                (+ y z)
                (+ x y)))
        ((< x z)
            (if (< x y)
                (+ y z)
                (+ x z)))
        ((< y z)
            (+ x z))
        (else (+ x y))))

(sum-of-two-max 1 2 3)
(sum-of-two-max 1 3 2)
(sum-of-two-max 2 1 3)
(sum-of-two-max 2 3 1)
(sum-of-two-max 3 1 2)
(sum-of-two-max 3 2 1)
