language: python
python:
  - '3.5'

install:
  # - pip3 install fabric3
  # - pip3 install ghp-import
  - pip3 install simiki

# after_script:
#   - cd output
#   - git init
#   - git config user.name "JMwill"
#   - git config user.email "787505998@qq.com"
#   - git add .
#   - git commit -m "Update Blog"
#   - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:gh-pages

script:
  - simiki g
  # - fab deploy

branches:
  only:
    - master

deploy:
  local_dir: output
  provider: pages
  skip_cleanup: true
  github_token: $GHPToken # Set in travis-ci.org dashboard
  on:
    branch: master

env:
  global:
    - GH_REF: github.com/JMwill/wiki.git